USE LibraryDB
GO

CREATE TABLE Users (
userID INT PRIMARY KEY IDENTITY,
fullName VARCHAR (255) NOT NULL,
userPassword VARCHAR (255) NOT NULL,
email VARCHAR (255) UNIQUE NOT NULL
)
GO

CREATE TABLE Books (
bookID INT PRIMARY KEY IDENTITY,
Title VARCHAR (255) NOT NULL,
Author VARCHAR (255) NOT NULL,
bookDescription VARCHAR(MAX) NOT NULL,
Avaliable BIT DEFAULT 1
)
GO

CREATE TABLE Borrow (
borrowID INT PRIMARY KEY IDENTITY,
userID INT NOT NULL,
bookID INT NOT NULL,
dateBorrowed DATETIME DEFAULT GETDATE(),
dateReturned DATETIME NULL,
CONSTRAINT userID FOREIGN KEY (userID) REFERENCES Users (userID),
CONSTRAINT bookID FOREIGN KEY (bookID) REFERENCES Books (bookID)
)
GO


